spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/biblioteka}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:123456789}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}